# Cloud Build configuration for Seller Inventory
# Triggers: Push to main branch
# Free tier: 120 build-minutes/day

substitutions:
  _REGION: us-central1  # FREE TIER: us-central1, us-east1, us-west1 only
  _API_SERVICE: sellerinventory-api
  _WEB_SERVICE: sellerinventory-web
  _GCS_BUCKET: sellerinventory-images

steps:
  # Step 1: Build API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'src/Api/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:latest'
      - '.'
    id: 'build-api'

  # Step 2: Build Web image (runs in parallel with API)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'src/Client/BlazorWeb/Dockerfile'
      - '--build-arg'
      - 'API_BASE_URL=https://${_API_SERVICE}-$PROJECT_ID.${_REGION}.run.app'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:latest'
      - '.'
    id: 'build-web'

  # Step 3: Push API image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA']
    id: 'push-api'
    waitFor: ['build-api']

  # Step 4: Push API latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_API_SERVICE}:latest']
    id: 'push-api-latest'
    waitFor: ['build-api']

  # Step 5: Push Web image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA']
    id: 'push-web'
    waitFor: ['build-web']

  # Step 6: Push Web latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:latest']
    id: 'push-web-latest'
    waitFor: ['build-web']

  # Step 7: Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_API_SERVICE}'
      - '--image=gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=2'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production'
      - '--set-env-vars=StorageProvider=GoogleCloud'
      - '--set-env-vars=GoogleCloud__BucketName=${_GCS_BUCKET}'
      - '--set-env-vars=JwtSettings__Issuer=SellerInventory'
      - '--set-env-vars=JwtSettings__Audience=SellerInventory'
      - '--set-env-vars=JwtSettings__ExpirationHours=24'
      - '--set-secrets=ConnectionStrings__DefaultConnection=database-url:latest'
      - '--set-secrets=JwtSettings__SecretKey=jwt-secret-key:latest'
    id: 'deploy-api'
    waitFor: ['push-api']

  # Step 8: Get API URL and deploy Web
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(gcloud run services describe ${_API_SERVICE} --region=${_REGION} --format="value(status.url)")
        gcloud run deploy ${_WEB_SERVICE} \
          --image=gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA \
          --platform=managed \
          --region=${_REGION} \
          --allow-unauthenticated \
          --port=80 \
          --memory=256Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=2

        WEB_URL=$(gcloud run services describe ${_WEB_SERVICE} --region=${_REGION} --format="value(status.url)")

        # Update API CORS with Web URL
        gcloud run services update ${_API_SERVICE} \
          --region=${_REGION} \
          --update-env-vars="AllowedOrigins__0=$${WEB_URL}"

        echo "Deployment complete!"
        echo "API: $${API_URL}"
        echo "Web: $${WEB_URL}"
    id: 'deploy-web'
    waitFor: ['deploy-api', 'push-web']

images:
  - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_API_SERVICE}:latest'
  - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_WEB_SERVICE}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
